version: '3'
services:
  ml:
    # Берем Dockerfile из каталога app
    build:
      context: .
      dockerfile: Dockerfile
#     Запускаем тестовый сервер
    command: uvicorn main:app --host 0.0.0.0 --port
    ports:
      - "8000:8000"