version: '3'
services:
  ml:
    # Берем Dockerfile из каталога app
    build:
      context: .
      dockerfile: Dockerfile
    # TODO
    restart: always
    # Запускаем тестовый сервер
    command: uvicorn main:app --host 0.0.0.0 --port 8000
    ports:
      - "8000:8000"